CREATE TABLE Categoria 
(
	ID_CATEGORIA INT PRIMARY KEY,
	NM_CATEGORIA VARCHAR(30)
)

GO
CREATE TABLE Usuario 
(
	ID_USUARIO INT PRIMARY KEY IDENTITY,
	USERNAME VARCHAR(50) UNIQUE,
	SENHA VARCHAR(50),
	ID_CATEGORIA INT REFERENCES Categoria(ID_CATEGORIA),
)

GO
CREATE TABLE Fundos_Usuario 
(
	ID_USUARIO INT REFERENCES Usuario(ID_USUARIO),
	CODIGO_FII VARCHAR(6), -- Códigos de FII's podem ser identificados por 4 letras é o código 11 ao final
	QTD_COTAS INT,
)