GO
CREATE TABLE Fundos_Usuario 
(
	ID_USUARIO INT References Usuario(ID_USUARIO),
	CODIGO_FII VARCHAR(6) UNIQUE,
	QTDCOTAS INT	
)

GO
INSERT INTO Categoria (ID_CATEGORIA INT, NM_CATEGORIA) VALUES (1, "Investidor Iniciante");
INSERT INTO Categoria (ID_CATEGORIA INT, NM_CATEGORIA) VALUES (2, "Investidor Intermediário");
INSERT INTO Categoria (ID_CATEGORIA INT, NM_CATEGORIA) VALUES (3, "Investidor Experiente");
INSERT INTO Categoria (ID_CATEGORIA INT, NM_CATEGORIA) VALUES (4, "Especulador");
INSERT INTO Categoria (ID_CATEGORIA INT, NM_CATEGORIA) VALUES (5, "Noob");
